dist: xenial
sudo: true
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.7
  - 3.8

env:
  global:
    - INSTALL=pip
    - CHECK=test
  matrix:
    - INSTALL=pip
    - INSTALL=install
    - INSTALL=develop
    - INSTALL=sdist
    - INSTALL=wheel

matrix:
  include:
    - python: 3.7
      env: CHECK=style

before_install:
  - travis_retry python -m pip install --upgrade pip setuptools wheel twine
  - |
    if [ "$INSTALL" = "sdist" ]; then
        python setup.py sdist
        twine check dist/niflow-manager*.tar.gz
    elif [ "$INSTALL" = "wheel" ]; then
        python setup.py bdist_wheel
        twine check dist/niflow_manager*.whl
    fi

install:
  - |
    if [ "$INSTALL" = "pip" ]; then
        pip install ".[test]"
    elif [ "$INSTALL" = "install" ]; then
        python setup.py install
    elif [ "$INSTALL" = "develop" ]; then
        python setup.py develop
    elif [ "$INSTALL" = "sdist" ]; then
        pip install "$( ls dist/niflow-manager*.tar.gz )[test]"
    elif [ "$INSTALL" = "wheel" ]; then
        pip install "$( ls dist/niflow_manager*.whl )[test]"
    fi
  - nfm --help  # Verify basic operation without test packages

before_script:
  - |
    if [ "$CHECK" = "style" ]; then
        pip install black
    elif [ "$CHECK" = "test" ]; then
        pip install pytest-cov coverage codecov
    fi

script:
  - |
    if [ "$CHECK" = "style" ]; then
        black --check --exclude templates/python setup.py niflow_manager
    elif [ "$CHECK" = "test" ]; then
        py.test -v -s --cov niflow_manager --cov-report xml:cov.xml --doctest-modules niflow_manager
    fi

after_script:
  - |
    if [ "$CHECK" = "test" ]; then
        codecov --file cov.xml --flags unittests -e TRAVIS_JOB_NUMBER
    fi
