dist: xenial
sudo: true

language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev

env:
  - INSTALL=sdist

matrix:
  include:
  - python: 3.7
    env: INSTALL=wheel


before_install:
  - travis_retry python -m pip install --upgrade pip setuptools wheel twine
  - |
    if [ "$INSTALL" = "sdist" ]; then
        python setup.py sdist
        twine check dist/niflow-manager*.tar.gz
    elif [ "$INSTALL" = "wheel" ]; then
        python setup.py bdist_wheel
        twine check dist/niflow_manager*.whl
    fi

install:
  - |
    if [ "$INSTALL" = "sdist" ]; then
        pip install "$( ls dist/niflow-manager*.tar.gz )[test]"
    elif [ "$INSTALL" = "wheel" ]; then
        pip install "$( ls dist/niflow_manager*.whl )[test]"
    fi

before_script:
  - travis_retry python -m pip install pytest-cov coverage codecov

script:
  - py.test -vs --cov niflow_manager --cov-report xml:cov.xml --doctest-modules niflow_manager

after_script:
  - codecov --file cov.xml --flags unittests -e TRAVIS_JOB_NUMBER
